# Generated by Django 4.1.7 on 2023-04-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='preview_text',
        ),
        migrations.AddField(
            model_name='answermark',
            name='is_like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmark',
            name='is_like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
