# Generated by Django 4.1.7 on 2023-04-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('login', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('popularity', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
    ]
