# Generated by Django 4.2.1 on 2023-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='popularity',
            field=models.BigIntegerField(default=0),
        ),
    ]
